name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_HUGGING_FACE_API_KEY: ${{ secrets.REACT_APP_HUGGING_FACE_API_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Frontend Dependencies
      run: npm install

    - name: Install Backend Dependencies
      run: |
        cd server
        npm install
        cd ..

    - name: Create env file
      run: |
        touch .env
        echo "REACT_APP_API_URL=${REACT_APP_API_URL}" >> .env
        echo "REACT_APP_HUGGING_FACE_API_KEY=${REACT_APP_HUGGING_FACE_API_KEY}" >> .env

    - name: Build Frontend
      run: npm run build
      env:
        CI: false

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: build
        clean: true
